### ISSUE TITLE
Email Id Should Be Lower Case

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/pranaw.murugesan__web_project_2#2]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiJiNGMxNTAxNC0zMmVlLTRmMDItYjNiNS1lMTQ5M2EzNDIxZmUifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiIzNDBjOGM4MS0xMTM1LTRiNmUtYTk1Mi02NjRkNjI5Mzg0ODkifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiI0Nzk3MWU1Mi0yNTU5LTRmNzQtODM5Mi04OGFkMGYyODc0YTYifQ==)

### Description of the issue
while signing up I gave my email id as a lower and upper character but while logging in I only gave the lower character 

### Expected result
Email Id will be lowercase only so while data storing in local storage I should save it in lowercase format 

### Actual result
while giving lower case email id in logging in to the form it throws an error

```
Path:      /login/signin.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 899 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--scryptify.netlify.app%2Flogin%2Fsignin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x899&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--scryptify.netlify.app/login/signin.html)

**Comment by cyber-sparky** [comment]
Now, I fixed the issue. Users can now input capital and small letters, in the javascript validation it will lowercase the email field. In the sign in form I did the same. So it will compares the localStorage ( converted into lowercase ) and login.

**Comment by aravindramvjs** [comment]
Great Work
