### ISSUE TITLE
Sidebar heading doesn't redirects to respective content

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/pranaw.murugesan__web_project_2#3]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiI0NjZjZmE5YS1lM2Q5LTRkMzUtOTVlMS05NDNjZWVmOTczY2MifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiJhODM1M2RlMC00OTk4LTQ4NDAtYjgxOS03MDhkNzMwNzUxNmIifQ==)

### Description of issue
The Sidebar heading doesn't redirect to the respective content

### Expected result
Sidebar heading should redirect to respective content

### Actual result
when I click How does hacking work it redirects correctly but whitehat, greyhat, and blackhat hacker is not redirecting to their respective content

```
Path:      /learning_pages/stagesofhacking
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 899 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--scryptify.netlify.app%2Flearning_pages%2Fstagesofhacking&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x899&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--scryptify.netlify.app/learning_pages/stagesofhacking)

**Comment by cyber-sparky** [comment]
Now the issue fixed.

**Comment by aravindramvjs** [comment]
great job pranaw
