### ISSUE TITLE
Redirection Issue

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/pranaw.murugesan__web_project_2#4]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiI1ZDBiM2NhZC02ZmRkLTRmMzMtOGUyMy1jYTFlNWFmZjU2YTEifQ==)

### Description of issue
In the Fun attacks with friends with friends webpage it should redirects to linux commands but it not redirecting 

### Expected result
In the Fun attacks with friends with friends webpage it should redirects to linux commands

### Actual result
In the Fun attacks with friends with friends webpage it should redirects to linux commands but it not redirecting 

```
Path:      /learning_pages/funattacks
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 899 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--scryptify.netlify.app%2Flearning_pages%2Ffunattacks&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x899&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--scryptify.netlify.app/learning_pages/funattacks)

**Comment by cyber-sparky** [comment]
Redirection error fixed.

**Comment by aravindramvjs** [comment]
good work pranaw
