### ISSUE TITLE
Validation Issue editing name

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/pranaw.murugesan__web_project_2#5]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiJiZDJkMTcwZi1jZTg2LTRhMzctYTdhOC01OWM4YTgzZjIxZjYifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGIzOGE1NDktNmUxZC00ODNmLWFlZDQtOTZkMGFmZmVmMTE1IiwiZGVwbG95X2lkIjoiNjQzYmQwOWQ1ZTlmMjgwMDA4NDhkNjk2IiwiaWQiOiI3NTYyMmI4NS05YTcxLTQxMzUtODFlYi02ZGY4YjJiNTc2ZmMifQ==)

### Description of issue
- The username can not contains spaces or number or special character but while editing name in user profile it allows all such case

### Expected result
It should validate name whether it is lowercase and there is no spaces or number or special character exists

### Actual result
it allows all lowercase or uppercase or number or special character

```
Path:      /profile/profile.html?fname=li++++++**********ght&lname=Ya+++++ga++++mi
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 899 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--scryptify.netlify.app%2Fprofile%2Fprofile.html%3Ffname%3Dli%2B%2B%2B%2B%2B%2B**********ght%26lname%3DYa%2B%2B%2B%2B%2Bga%2B%2B%2B%2Bmi&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x899&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--scryptify.netlify.app/profile/profile.html?fname=li++++++**********ght&lname=Ya+++++ga++++mi)

**Comment by cyber-sparky** [comment]
Issue fixed

**Comment by aravindramvjs** [comment]
Good Work Pranaw
